USE movies

--1
select M.TITLE, M.YEAR, M.LENGTH
FROM MOVIE M
WHERE M.YEAR < 2000 
AND M.LENGTH > 120
OR M.LENGTH IS NULL

--2
SELECT M.NAME, M.GENDER
FROM MOVIESTAR M
WHERE M.NAME LIKE 'J%'
AND YEAR(M.BIRTHDATE) > 1948
ORDER BY M.NAME DESC

--3
SELECT M.STUDIONAME, COUNT(DISTINCT S.STARNAME)
FROM MOVIE M
JOIN STARSIN S ON M.TITLE=S.MOVIETITLE
GROUP BY M.STUDIONAME

--4
SELECT S.STARNAME, COUNT(DISTINCT S.MOVIETITLE)
FROM STARSIN S 
GROUP BY S.STARNAME

--5
SELECT M.STUDIONAME, M.TITLE,M.YEAR
FROM MOVIE M
WHERE M.YEAR = (
	SELECT MAX(M2.YEAR)
	FROM MOVIE M2
	WHERE M2.STUDIONAME=M.STUDIONAME)

--6
SELECT M.NAME
FROM MOVIESTAR M
WHERE M.BIRTHDATE = 
(
	SELECT MAX(S.BIRTHDATE)
	FROM MOVIESTAR S
	WHERE S.GENDER='M'
)

--7

SELECT DISTINCT M.STUDIONAME, S.STARNAME, COUNT(S.MOVIETITLE)
FROM STARSIN S
JOIN MOVIE M ON M.TITLE=S.MOVIETITLE
GROUP BY S.STARNAME, M.STUDIONAME
HAVING COUNT(M.TITLE) >= ALL
( SELECT COUNT(S2.MOVIETITLE)
  FROM STARSIN S2
  JOIN MOVIE M2 ON M2.TITLE=S2.MOVIETITLE
  WHERE M2.STUDIONAME=M.STUDIONAME
  GROUP BY M2.STUDIONAME, S2.STARNAME)

--8

SELECT M.TITLE,M.YEAR, COUNT(S.STARNAME)
FROM MOVIE M 
JOIN STARSIN S ON S.MOVIETITLE=M.TITLE
GROUP BY M.TITLE, M.YEAR
HAVING COUNT(S.STARNAME) >2

--------
USE ships

--1
SELECT DISTINCT S.NAME
FROM ships S
JOIN OUTCOMES O ON O.SHIP=S.NAME
WHERE S.NAME LIKE 'C%' OR S.NAME LIKE 'K%'

--2
SELECT S.NAME, C.COUNTRY
FROM SHIPS S
JOIN CLASSES C ON C.CLASS=S.CLASS
WHERE S.NAME NOT IN (SELECT O.SHIP
					 FROM OUTCOMES O)
OR S.NAME IN (SELECT O2.SHIP
			  FROM OUTCOMES O2
			  WHERE O2.RESULT NOT LIKE 'sunk')

--3
SELECT C.COUNTRY, COUNT(O.SHIP)
FROM SHIPS S
  RIGHT JOIN CLASSES C ON C.CLASS=S.CLASS
  LEFT JOIN OUTCOMES O ON O.SHIP=S.NAME
WHERE O.RESULT='sunk' OR O.RESULT IS NULL
GROUP BY C.COUNTRY

--4
SELECT O.BATTLE
FROM OUTCOMES O
GROUP BY O.BATTLE
HAVING COUNT(O.SHIP) >
(SELECT COUNT (O1.SHIP)
 FROM OUTCOMES O1
 WHERE O1.BATTLE = 'Guadalcanal')

 --5
 SELECT O.BATTLE
FROM OUTCOMES O
GROUP BY O.BATTLE
HAVING COUNT(O.SHIP) >
(SELECT COUNT (O1.SHIP)
 FROM OUTCOMES O1
 WHERE O1.BATTLE = 'Surigao Strait')

 --6
 SELECT S.NAME,MIN(C.DISPLACEMENT), MAX(C.NUMGUNS)
 FROM CLASSES C JOIN SHIPS S ON S.CLASS=C.CLASS
 WHERE C.DISPLACEMENT =
    (SELECT MIN(C.DISPLACEMENT)
	FROM CLASSES C
	WHERE C.NUMGUNS =
    (SELECT MAX(C2.NUMGUNS)
    FROM CLASSES C2
    WHERE C.DISPLACEMENT=C2.DISPLACEMENT) )
GROUP BY S.NAME


----7
SELECT COUNT(O.SHIP)
FROM OUTCOMES O
JOIN BATTLES B ON B.NAME=O.BATTLE
WHERE O.RESULT='damaged' AND B.DATE < 
(SELECT MAX(B2.DATE)
 FROM BATTLES B2
 JOIN OUTCOMES O2 ON O2.BATTLE=B2.NAME
 WHERE O2.SHIP=O.SHIP)

 --8
 SELECT O.SHIP
FROM OUTCOMES O
JOIN BATTLES B ON B.NAME=O.BATTLE
GROUP BY O.SHIP, O.RESULT, B.DATE
HAVING O.RESULT='ok' 
AND B.DATE >
		(SELECT B2.DATE
		 FROM OUTCOMES O2 
		 JOIN BATTLES B2 ON B2.NAME=O2.BATTLE
		 WHERE O.SHIP=O2.SHIP
		 GROUP BY O2.SHIP, O2.RESULT, B2.DATE
		 HAVING O2.RESULT='damaged')
AND COUNT(O.SHIP) >= (
		SELECT COUNT(O2.SHIP)
		FROM OUTCOMES O2
		JOIN BATTLES B2 ON B2.NAME=O2.BATTLE
		WHERE O2.SHIP=O.SHIP
		GROUP BY O2.BATTLE, O2.RESULT, B2.DATE
		HAVING O2.RESULT='damaged')

----
use pc

--1
SELECT DISTINCT L.model, L.code, L.screen
FROM laptop L
JOIN LAPTOP L2 ON L2.model=L.MODEL
WHERE L.screen = 15 OR L.screen = 11

--2
SELECT DISTINCT P.model
FROM product PR
JOIN PC P ON P.model=PR.model
WHERE P.price < ALL (
		SELECT MIN(L.price)
		FROM laptop L
		WHERE L.model IN 
				(SELECT R.model
				 FROM product R
				 WHERE R.maker=PR.maker) )

--3
SELECT P.model, AVG(P.price)
FROM product PR
JOIN PC P ON P.model=PR.model
GROUP BY P.model, PR.maker
HAVING AVG(P.price)< ALL (
		SELECT MIN(L.price)
		FROM laptop L
		WHERE L.model IN 
				(SELECT R.model
				 FROM product R
				 WHERE R.maker=PR.maker) )

--4
SELECT P.code, PR.maker, (SELECT COUNT(P2.code)
                          FROM pc P2
                          WHERE P2.price >= P.price)
FROM PC P
JOIN product PR ON PR.model=P.model
GROUP BY P.code, PR.maker, P.price









 




