--1
USE movies

--1
SELECT M.TITLE, E.NAME
FROM MOVIEEXEC E
JOIN MOVIE M ON E.CERT#=M.PRODUCERC#
where M.PRODUCERC# = (SELECT MV.PRODUCERC#
					  FROM MOVIE MV
					  WHERE TITLE = 'Star Wars')

--2
SELECT DISTINCT E.NAME
FROM MOVIEEXEC E
JOIN MOVIE M ON M.PRODUCERC# = E.CERT#
WHERE M.PRODUCERC# in (SELECT M.PRODUCERC#
					  from MOVIE
					  WHERE M.TITLE IN (SELECT S.MOVIETITLE
										FROM STARSIN S
										WHERE S.STARNAME='Harrison Ford'))

--3
SELECT DISTINCT S.STUDIONAME,  SS.STARNAME
FROM MOVIE S
JOIN STARSIN SS ON SS.MOVIETITLE = S.TITLE

--4
SELECT S.STARNAME, E.NETWORTH, M.TITLE
FROM MOVIE M
JOIN STARSIN S ON S.MOVIETITLE = M.TITLE
JOIN MOVIEEXEC E ON E.CERT# = M.PRODUCERC#
WHERE E.NETWORTH >= ALL (SELECT ME.NETWORTH
						FROM MOVIEEXEC ME)

--5----
SELECT DISTINCT MS.NAME
FROM MOVIESTAR MS
left JOIN STARSIN S ON S.STARNAME = MS.NAME
WHERE S.MOVIETITLE IS NULL
--2
USE pc

--1
SELECT P.maker, P.model, P.type
FROM product P
LEFT JOIN pc C ON C.model = P.model
LEFT JOIN printer R ON R.model = P.model
LEFT JOIN laptop L ON L.model = P.model
WHERE C.model IS NULL AND R.model IS NULL AND L.model IS NULL

--2
SELECT DISTINCT R1.maker
FROM product R1
JOIN laptop C ON C.model = R1.model 
JOIN product R2 ON R2.maker = R1.maker
JOIN PRINTER P ON P.MODEL = R2.MODEL

--3
SELECT DISTINCT L.hd
FROM laptop L
JOIN laptop L2 ON L.hd = L2.hd
WHERE NOT L.code = L2.code

--4
SELECT P.model
FROM PC P
LEFT JOIN product R ON R.model = P.model
WHERE R.model IS NULL

--3
USE ships

--1
SELECT DISTINCT S.*, C.*
FROM SHIPS S
LEFT JOIN CLASSES C ON C.CLASS = S.CLASS

--2
SELECT DISTINCT S1.*, C.*
FROM SHIPS S1
FULL JOIN CLASSES C ON C.CLASS = S1.CLASS
WHERE C.CLASS IN (SELECT S2.NAME
				  FROM SHIPS S2)

--3
SELECT C.COUNTRY, S.NAME
FROM  SHIPS S
JOIN CLASSES C ON C.CLASS = S.CLASS
LEFT JOIN OUTCOMES O ON O.SHIP = S.NAME
WHERE O.SHIP IS NULL
ORDER BY C.COUNTRY

--4
SELECT S.NAME AS 'Ship name'
FROM CLASSES C
JOIN SHIPS S ON S.CLASS=C.CLASS
WHERE C.NUMGUNS > 7 AND S.LAUNCHED = 1916

--5
SELECT O.SHIP, O.BATTLE, B.DATE 
FROM OUTCOMES O
JOIN BATTLES B ON B.NAME = O.BATTLE
WHERE O.RESULT = 'sunk'

--6
SELECT s.NAME, C.DISPLACEMENT, S.LAUNCHED
FROM SHIPS S
JOIN CLASSES C ON C.CLASS=S.CLASS
WHERE C.CLASS = S.NAME

--7
SELECT C.*
FROM CLASSES C
LEFT JOIN SHIPS S ON S.CLASS = C.CLASS
WHERE S.CLASS IS NULL

--8
SELECT S.NAME, C.DISPLACEMENT, C.NUMGUNS, O.RESULT
FROM SHIPS S
JOIN OUTCOMES O ON S.NAME = O.SHIP
JOIN CLASSES C ON C.CLASS = S.CLASS
WHERE O.BATTLE = 'North Atlantic'



