USE movies

SELECT ADDRESS FROM STUDIO
WHERE NAME = 'Disney'

SELECT BIRTHDATE FROM MOVIESTAR
WHERE NAME = 'Jack Nicholson'

SELECT STARNAME FROM STARSIN
WHERE MOVIETITLE LIKE '%Knight%' OR MOVIEYEAR = 1980

SELECT NAME FROM MOVIEEXEC
WHERE NETWORTH >= 10000000

SELECT NAME FROM MOVIESTAR
WHERE GENDER = 'M' OR ADDRESS = 'Prefect Rd.'

USE pc

SELECT model AS 'MODEL',
	  speed AS 'MHZ',
	  hd AS 'GB' FROM pc
WHERE price < 1200

SELECT DISTINCT maker FROM product
WHERE type = 'Printer'

SELECT model AS 'MODEL',
	   ram AS 'RAM',
	   screen AS 'SCREEN' FROM laptop
WHERE price > 1000

SELECT * FROM printer
WHERE color = 'y'

SELECT model AS 'MODEL',
	  speed AS 'SPEED',
	  hd AS 'HD' FROM pc
WHERE (cd = '12x' OR cd = '16x') AND price < 2000


USE ships

SELECT CLASS, COUNTRY FROM CLASSES
WHERE NUMGUNS < 10

SELECT  NAME AS SHIPNAME
FROM      SHIPS
WHERE   (LAUNCHED < 1918)

SELECT  SHIP, BATTLE
FROM      OUTCOMES
WHERE   (RESULT = 'sunk')

SELECT NAME FROM SHIPS
WHERE NAME = CLASS

SELECT NAME FROM SHIPS 
WHERE NAME LIKE 'R%'

SELECT NAME FROM SHIPS
WHERE NAME LIKE '%% %%'


